### ISSUE TITLE
Has anyone got this to work on Tableau Server?

### ISSUE THREAD

**Issue by jjscarlett** [xHeliotrope/redcap-wdc#3]
I have followed the instructions to white-list the WDC url and supporting files (https://onlinehelp.tableau.com/current/server/en-us/tabadmin_cmd.htm#whitelist_wdc). But when I trigger the refresh on the server, it runs until it times out (7200s).

Just wondering if anyone has gotten this to work on a Tableau Server.
Cheers
Jason

**Comment by xHeliotrope** [comment]
if the entire page is timing out then its a tableau administration issue.

when hosting the connector on your tableau server, you only need to upload the **redcap_wdc.html**. You could check the tableau server admin logs to see why the page is timing out. I believe its **tabadmin.log**. 

https://onlinehelp.tableau.com/current/server/en-us/logs_loc.htm

**Comment by jjscarlett** [comment]
Okay will do some more digging in the log files ... I wonder if the RedCap server not having SSL could be an issue.
Did you use the white-list or import method?

**Comment by jjscarlett** [comment]
I got it to work with the import method!
... but only if I used http instead of https ... I think our certificate is not externally verified or whatever. :)

**Comment by xHeliotrope** [comment]
Cool! Glad you got it set up.

Its possible that ssl needs to be configured/enabled on your tableau server
(tableau has docs on how to do this). Its also possible that its an issue
that tableau needs to fix with their data connectors (see
https://serverfault.com/questions/875965/ssl-handshake-failed-when-trying-to-connect-to-a-tableau-web-data-connector-fr
).

**Comment by jjscarlett** [comment]
I did some more digging and now have both the import and white-list methods working.
I think the SSL error was my fault .. I blindly used the URL that the import function provided ... it had https but did not use the full/correct domain name.

Any ways, thanks, and this RedCap WDC is a big help.
